# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('image_file', models.FilePathField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HatTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='hatparty.Hat')),
            ],
        ),
        migrations.CreateModel(
            name='HatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField()),
                ('current_hat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_wearer', to='hatparty.Hat')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_likes', to='hatparty.HatUser')),
                ('hat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_likes', to='hatparty.Hat')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_likes', to='hatparty.HatUser')),
            ],
        ),
        migrations.CreateModel(
            name='Slap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_slaps', to='hatparty.HatUser')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_slaps', to='hatparty.HatUser')),
            ],
        ),
        migrations.AddField(
            model_name='hattransfer',
            name='source_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='hatparty.HatUser'),
        ),
        migrations.AddField(
            model_name='hattransfer',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='hatparty.HatUser'),
        ),
    ]
