# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hatparty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatuser',
            name='auth_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
