# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatparty', '0002_auto_20160812_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='image_file',
            field=models.FilePathField(null=True),
        ),
    ]
