# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatparty', '0002_hatuser_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatuser',
            name='current_hat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_current_wearer', to='hatparty.Hat'),
        ),
    ]
