# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 04:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatparty', '0003_auto_20160812_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='hattransfer',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='like',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='slap',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='hat',
            name='image_file',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hatuser',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='hatuser',
            name='current_hat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_wearer', to='hatparty.Hat'),
        ),
    ]
