# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hatparty', '0004_auto_20160812_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hattransfer',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hatuser',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='like',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slap',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
