# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatparty', '0005_auto_20160812_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatuser',
            name='counter_value',
            field=models.IntegerField(default=0),
        ),
    ]
