# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatparty', '0006_hatuser_counter_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hatuser',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hat',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hatuser',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
