# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hatparty', '0007_auto_20160812_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hattransfer',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='hatparty.HatUser'),
        ),
    ]
